url: "https://macho199.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "macho199 Blog" # the name of your site, e.g. ACME Corp.
description: >- # this means to ignore newlines until "baseurl:"
  Programming, IT Trend, Story, PHP, Javascript, Python, Docker
author: "js Kwon"
lang: "ko-KR"

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/logo.png

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: UA-144643589-1
naver_site_verification: 220660cdee890bd65b43a769fc7ad1d5ec04ed56

twitter:
  username: macho1999
  card: summary

facebook:
  app_id: 331647774455773
  publisher: https://www.facebook.com/macho199/
