import "@fontsource/noto-serif-kr/400.css"
import "@fontsource/noto-sans-kr/400.css"
import "@fontsource/noto-sans-kr/500.css"
import "@fontsource/noto-sans-kr/600.css"

import "./src/styles/theme.css"
import "./src/styles/mdx.css"
import "./src/styles/layout.css"
import "./src/styles/home.css"
import "./src/styles/post.css"
import "./src/styles/portfolio.css"
